version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ippmis_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - ippmis_network

  nginx:
    image: nginx:stable-alpine
    container_name: ippmis_nginx
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "8443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/ssl:/etc/nginx/ssl:roy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ippmis_network

networks:
  ippmis_network:
    driver: bridge






