version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queuing_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - ippmis_network

  nginx:
    image: nginx:stable-alpine
    container_name: queuing_nginx
    restart: unless-stopped
    ports:
      - "8087:8087"
      - "8448:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/ssl:/etc/nginx/ssl:roy
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - queuing_network

networks:
  queuing_network:
    driver: bridge






