services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queuing-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - laravel-network
    ports:
      - '2352:80'

networks:
  laravel-network:
    driver: bridge
